QUESTIONS = [
    #EASY
    {"question": "What year was the Constitution of Nepal adopted?", 
    "answer": "2072"},
    {"question": "What is the highest law in Nepal?", 
    "answer": "The Constitution of Nepal"},
    {"question": "Which body has the authority to amend the Constitution of Nepal?", 
    "answer": "The Parliament of Nepal"},
    {"question": "What are the seven provinces of Nepal called?", 
    "answer": "The provinces are: Province No. 1, Province No. 2, Bagmati Province, Gandaki Province, Lumbini Province, Karnali Province, and Sudurpashchim Province."},
    {"question": "Who is the head of state according to the Constitution of Nepal?", 
    "answer": "The President of Nepal"},
    {"question": "What type of government does the Constitution of Nepal establish?", 
    "answer": "A federal democratic republic"},
    {"question": "What is the main language used in the Constitution of Nepal?", 
    "answer": "Nepali"},
    {"question": "How many articles are there in the Constitution of Nepal?", 
    "answer": "The Constitution has 308 articles."},
    {"question": "What fundamental rights are guaranteed by the Constitution of Nepal?", 
    "answer": "Fundamental rights include the right to equality, freedom of speech, freedom of assembly, right to education, and right to protection against discrimination, among others."},
    {"question": "What does the Constitution of Nepal say about the official religion of the country?", 
    "answer": "The Constitution declares Nepal as a secular state, meaning it does not endorse any official religion."},
    # "Medium
    {"question": "What is the term length for the President of Nepal according to the Constitution?", 
    "answer": "The President of Nepal is elected for a term of five years."},
    {"question": "Which body in Nepal is responsible for interpreting the Constitution?", 
    "answer": "The Supreme Court of Nepal is responsible for interpreting the Constitution."},
    {"question": "What is the process for selecting the Prime Minister of Nepal according to the Constitution?", 
    "answer": "The Prime Minister of Nepal is appointed by the President based on the majority support in the House of Representatives."},
    {"question": "Which constitutional article defines the state structure of Nepal?", 
    "answer": "Article 56 of the Constitution of Nepal defines the federal structure of the state."},
    {"question": "How is the federal structure of Nepal divided according to the Constitution?", 
    "answer": "The federal structure of Nepal is divided into seven provinces."},
    {"question": "What is the role of the National Assembly in the context of Nepal's Constitution?", 
    "answer": "The National Assembly is one of the two houses of Parliament and is responsible for passing laws, along with the House of Representatives."},
    {"question": "What provision does the Constitution of Nepal make regarding the protection of minority rights?", 
    "answer": "The Constitution provides for the protection and promotion of the rights of minorities, including cultural, linguistic, and religious rights."},
    {"question": "Which document is considered the supreme legal authority in Nepal?", 
    "answer": "The Constitution of Nepal is considered the supreme legal authority."},
    {"question": "What mechanism does the Constitution of Nepal provide for the dissolution of the House of Representatives?", 
    "answer": "The President has the authority to dissolve the House of Representatives on the recommendation of the Prime Minister."},
    {"question": "How does the Constitution of Nepal address gender equality?", 
    "answer": "The Constitution guarantees gender equality and prohibits discrimination based on gender, ensuring equal rights and opportunities for women."},
    # Hard
    {"question": "What are the primary functions of the Executive branch under the Constitution of Nepal?", 
    "answer": "The Executive branch is responsible for implementing laws, managing government affairs, and overseeing various ministries and departments. It is headed by the Prime Minister, who is appointed by the President."},
    {"question": "Can you explain the role of the Federal Parliament in Nepal's Constitution?", 
    "answer": "The Federal Parliament of Nepal consists of two houses: the House of Representatives and the National Assembly. It is responsible for making laws, approving budgets, and overseeing the executive branch. The Parliament plays a crucial role in the governance of the country by debating and passing legislation."},
    {"question": "How does the Constitution of Nepal address the distribution of powers between the central government and provincial governments?", 
    "answer": "The Constitution of Nepal establishes a federal system where powers are divided between the central government and the provincial governments. The central government handles national defense, foreign affairs, and national economic policies, while provincial governments are responsible for local administration, development, and other regional matters."},
    {"question": "What are the provisions related to citizenship under the Constitution of Nepal?", 
    "answer": "The Constitution of Nepal provides for two types of citizenship: by descent and by naturalization. It ensures that every citizen has the right to obtain citizenship and be recognized as a citizen of Nepal, with provisions for both individuals born to Nepali parents and those who meet specific criteria for naturalization."},
    {"question": "How does the Constitution of Nepal ensure the protection of human rights?", 
    "answer": "The Constitution guarantees a broad range of fundamental rights, including the right to equality, freedom of expression, and protection against discrimination. It establishes mechanisms for safeguarding these rights and provides for the judiciary to address violations and ensure compliance with human rights standards."},
    {"question": "What is the role of the judiciary in the Constitution of Nepal?", 
    "answer": "The judiciary in Nepal is independent and is responsible for interpreting laws, including the Constitution. It resolves disputes, ensures justice, and upholds the rule of law. The Supreme Court is the highest court and has the authority to review laws and executive actions for constitutionality."},
    {"question": "Describe the process for amending the Constitution of Nepal.", 
    "answer": "Amendments to the Constitution of Nepal can be proposed by the Parliament. An amendment requires a two-thirds majority in both the House of Representatives and the National Assembly. Some amendments also require approval by a majority of the provincial assemblies."},
    {"question": "What is the significance of the preamble in the Constitution of Nepal?", 
    "answer": "The preamble of the Constitution outlines the fundamental values, principles, and objectives of the Constitution. It reflects the aspirations of the people of Nepal and sets the framework for the governance and legal structure of the country."},
    {"question": "How does the Constitution of Nepal address the issue of federalism?", 
    "answer": "The Constitution of Nepal establishes a federal structure, dividing the country into seven provinces. It delineates the powers and responsibilities of each level of government, aiming to balance central authority with regional autonomy and ensure effective local governance."},
    {"question": "What are the key features of the electoral system as defined by the Constitution of Nepal?", 
    "answer": "The electoral system in Nepal involves a mixed system of first-past-the-post and proportional representation. The Constitution provides for elections to the House of Representatives, the National Assembly, and provincial assemblies, ensuring democratic representation at both national and local levels."}
  ]
