QUESTIONS = [
  { "question": "Who is vested with Sovereignty  and  state  authority?",
  "answer": """ The  sovereignty  and  state  authority  of  Nepal  shall be vested in the Nepalese people""" },
  { "question": "What is the fundamental law of Nepal?",
  "answer": """The Constitution is the fundamental law of Nepal""" },
  { "question": "What is the official language?",
  "answer": """Nepali""" },
  { "question": "What are the different languages spoken?",
  "answer": """All languages spoken as the mother tongues in Nepalare the languages of the nation""" },
  { "question": "Describe the National Flag.",
  "answer": """The national flag of Nepal consists of two juxtaposed triangular figures  with  a  crimson-coloured  base  and  deep  blue  borders,  there  being  a  white emblem  of  the  crescent  moon  with  eight  rays  visible  out  of  sixteen  in  the  upper part and a white emblem of a twelve rayed sun in the lower part.""" },
  { "question": "What should the territory of Nepal comprise?",
  "answer": """Territory at the time of commencement of constitution and may be acquired after the commencement""" },
  { "question": "What is the criteria for being a citizen of Nepal?",
  "answer": """Person with Permanent Domicile, Descent, Parents, Minors in Nepal, Born in Nepal, Foreign Woman with Matrimony in Nepal""" },
  { "question": "How can citizenship be granted to non-resident Nepalese?",
  "answer": """The non-residential citizenship of Nepal may be so granted to a person who has acquired the citizenship of a foreign country, has resided in a country other than a member state of  the  South  Asian  Association  for  Regional  Cooperation,  and  who  or  whose father or mother, grandfather or grandmother was previously a citizen of Nepal by decent  or  birth  but  subsequently  acquired  the  citizenship  of  the  foreign  country that  such  person  may  enjoy  economic,  social  and  cultural  rights  in  accordance with the Federal law.""" },
  { "question": "List out the different rights provided to Nepalese people.",
  "answer": """Senior Citizens, Social Security, Dignity, Freedom, Right to Equality, Communication ...""" },
  { "question": "How is equality defined for Nepalese?",
  "answer": """All Citizen equal, No discrimination through race, religion, cast, tribe, sex, economic condition, language, region, ideology or on other similar grounds.""" },
  { "question": "Who is eligible to own property in Nepal?",
  "answer": """Every citizen shall, subject to law, have the right to  acquire,  own,  sell,  dispose,  acquire  business  profits  from,  and  otherwise  deal with, property.""" },
  { "question": "What are the religion that Nepalese people are allowed to follow?",
  "answer": """Secular Nation""" },
  { "question": "Are there any specific rights provided to women?",
  "answer": """Social Security""" },
  { "question": "Describe the structure of the States in Nepal.",
  "answer": """Federalism""" },
  { "question": "Describe the distribution of state power.",
  "answer": """Federal Government -> State Government -> Local Government""" },
  { "question": "What are the sources of state revenue?",
  "answer": """Federal  Consolidated  Fund""" },
  { "question": "How is the election of president conducted?",
  "answer": """The  President  shall  be  elected  by  an  electoral  college composed of the members of the Federal Parliament and of the State Assemblies. The voting weight age of the members of the Federal Parliament and of the State Assemblies shall vary as provided for in the Federal law.""" },
  { "question": "What is the required qualification for being a president of Nepal?",
  "answer": """(a) being qualified to become a member of the Federal Parliament, (b) having completed the age of at least forty five years, and (c) not being disqualified by any law.""" },
  { "question": "Who has the ability to withdraw a bill?",
  "answer": """member who has introduced a Bill may, with the approval of the State Assembly, withdraw the Bill""" },
  { "question": "What is the council of Ministers?",
  "answer": """Group appointed by the President based on the majority party in the House of Representatives""" },
  { "question": "How is house of representatives formed?",
  "answer": """(a) One  hundred  and  sixty  five  members  to  be  elected  through  the  first past  the  post  electoral  system,  with  one  being  elected  from  each election constituency of one hundred and sixty five election constituencies  delimited  in  the  country  on  the  basis  of  geography and population, (b) One hundred and ten members to be elected through the proportional electoral  system  where  voters  vote  for  political  parties,  with  the whole country being considered as a single election constituency""" },
  { "question": "Who can be the chariperson of National Assembly?",
  "answer": """a candidate must be a member of the National Assembly and meet certain qualifications, such as being a citizen of Nepal and at least 35 years old. The election of the Chairperson is conducted by the members of the National Assembly itself.""" },
  { "question": "What is the Federal contingency fund?",
  "answer": """A  Federal Act may create  a fund to  be known as the  contingency  fund  into  which  such  moneys  as  may  be  determined  by  the Federal Act shall be paid from time to time.""" },
  { "question": "List the different types of courts.",
  "answer": """Supreme Court, High Court, District Court""" },
  { "question": "Describe the Qualifications required to be Chief of Justice in the supreme court.",
  "answer": """President Appoints. Should be a judge of the supreme court for at least 3 years""" },
  { "question": "What are the duties of Attorney General?",
  "answer": """Enforce legal rights.""" },
  { "question": "What is State Consolidated Fund?",
  "answer": """Except for the revenues of trusts, all revenues received by the State Government, all loans raised on the security of revenues, all moneys received in repayment of any loans made under the authority of any State Act  and  any  mounts  of  grants  or  loans  received  from  the  Government  of  Nepal shall,  except  as  otherwise  provided  for  in  the  State  Act,  be  credited  to  a  State Government Fund to be known as the State Consolidated Fund.""" },
  { "question": "What is the procedure for passage of Bills?",
  "answer": """(1) A Bill passed by the State Assembly shall be presented to the Chief of State for assent. (2)  If  a  session  of  the  State  Assembly  terminates  while  a  Bill  is  under consideration, deliberations on the Bill may continue at the succeeding session.""" },
  { "question": "How is a municipal assembly composed?",
  "answer": """Choice of the citizens""" },
  { "question": "Who has the power to make law?",
  "answer": """The Federal Parliament holds the power to make law""" }
]
